name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Verify Java Version
        run: java -version

      - name: Verify Maven Version
        run: mvn -version

      - name: Build Java Project
        run: mvn clean package

      - name: Run Unit Tests
        run: mvn test

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-artifact
          path: target/*.jar
