name: Java sdf WAR CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # Install Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # Verify Java
      - name: Verify Java Version
        run: java -version

      # Verify Maven
      - name: Verify Maven Version
        run: mvn -version

      # Build WAR file
      - name: Build WAR Project
        run: mvn clean package

      # Run Tests
      - name: Run Unit Tests
        run: mvn test

      # Display target folder contents
      - name: List target folder
        run: ls -la target

      # Upload WAR Artifact
      - name: Upload WAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-war-artifact
          path: target/*.war
